base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: 'NO'
ec2_instance_type: ml.p3.8xlarge
iam_role_name: accelerate_sagemaker_execution_role
image_uri: null
mixed_precision: 'No'
num_machines: 1
profile: default
py_version: py38
pytorch_version: 1.10.2
region: eu-west-2
sagemaker_inputs_file: null
sagemaker_metrics_file: null
transformers_version: 4.17.0
use_cpu: false
